name: Build and Release Packages

on:
  push:
    tags:
      - 'v*'

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y rpm

      - name: Configure CMake
        run: cmake -H. -B_build

      - name: build project
        run: cmake --build _build

      - name: build TGZ package
        run: cpack -G "TGZ" -B _build --config _build/CPackConfig.cmake

      - name: build DEB package
        run: cpack -G "DEB" -B _build --config _build/CPackConfig.cmake

      - name: build RPM package
        run: cpack -G "RPM" -B _build --config _build/CPackConfig.cmake

      - name: upload packages to release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            _build/*.tar.gz
            _build/*.deb
            _build/*.rpm
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  macos:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure CMake
        run: cmake -H. -B ${{ github.workspace}}/_build

      - name: build project
        run: cmake --build ${{ github.workspace}}/_build

      - name: build TGZ package
        run: cpack -G "TGZ" -B ${{ github.workspace}}/_build --config ${{ github.workspace}}/_build/CPackConfig.cmake

      - name: build DMG package
        run: cpack -G "DragNDrop" -B ${{ github.workspace}}/_build --config ${{ github.workspace}}/_build/CPackConfig.cmake

      - name: upload packages to release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            _build/*.tar.gz
            _build/*.dmg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install WIX
        run: choco install wixtoolset -y

      - name: Configure CMake
        run: cmake -S. -B ${{ github.workspace}}/_build

      - name: build project
        run: cmake --build ${{ github.workspace}}/_build --config Release

      - name: build ZIP package
        run: cpack -G "ZIP" -B ${{ github.workspace}}/_build -C Release --config ${{ github.workspace}}/_build/CPackConfig.cmake

      - name: build MSI package
        run: cpack -G "WIX" -B ${{ github.workspace}}/_build -C Release --config ${{ github.workspace}}/_build/CPackConfig.cmake --parallel

      - name: upload packages to release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            _build/*.zip
            _build/*.msi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}